@echo off
echo Starting PHY2...
call C:\ProgramData\anaconda3\Scripts\activate.bat phy2 
echo PHY2 environment activated...
@SET /p param_path=Enter Params.py file path:
@CALL phy template-gui %param_path%\params.py
